# Generated by Django 6.1 on 2026-08-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('battery_health', models.IntegerField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20)),
                ('warranty', models.CharField(max_length=100)),
                ('box', models.BooleanField(default=True)),
                ('charger', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
        ),
    ]
